import type {Gen} from '@fuzdev/gro/gen.ts';
import {join} from 'node:path';
import {package_json_load} from '@fuzdev/gro/package_json.ts';

import {create_atom_feed} from './feed.ts';
import {collect_blog_post_ids, load_blog_post_modules, load_blogs_module} from './blog_helpers.ts';
import {resolve_blog_post_item, type BlogFeed} from './blog.ts';

/** @nodocs */
export const gen: Gen = async ({origin_path}) => {
	const package_json = await package_json_load();
	const fuz_blog_import_path =
		package_json.name === '@fuzdev/fuz_blog' ? '$lib' : '@fuzdev/fuz_blog';

	const dir = process.cwd();
	const routes_path = 'src/routes'; // TODO read from SvelteKit config;

	const {blogs} = await load_blogs_module(dir);

	const outputs: Array<{filename: string; content: string}> = [];

	for (const config of blogs) {
		const {dirname, feed: blog} = config;
		const slug_routes = config.slug_routes ?? true;
		const blog_dir = join(dir, routes_path, dirname);

		const blog_post_ids = collect_blog_post_ids(blog_dir);

		const modules = await load_blog_post_modules(blog_dir, blog_post_ids);

		// TODO zod schema validation including parsing the status context url (with zod?)
		// for (const mod of modules) {
		// 	validate_blog_post(mod.post)
		// }

		const items = modules.map((mod, i) =>
			resolve_blog_post_item(i + 1, blog.home_page_url, mod.post, {slug_routes}),
		);

		const feed: BlogFeed = {...blog, items};

		outputs.push({
			filename: join(dir, 'static', dirname, 'feed.xml'),
			content: create_atom_feed(feed),
		});

		outputs.push({
			filename: join(blog_dir, 'feed.ts'),
			content: `
				// generated by ${origin_path}

				import type {BlogFeed} from '${fuz_blog_import_path}/blog.ts';

				export const feed: BlogFeed = ${JSON.stringify(feed)}

				// generated by ${origin_path}
			`,
		});

		if (slug_routes) {
			for (const [i, mod] of modules.entries()) {
				const slug = mod.post.slug;
				const blog_post_id = i + 1;
				outputs.push({
					filename: join(blog_dir, slug, '+page.svelte'),
					content: `
							<!-- generated by ${origin_path} -->

							<script lang="ts">
								import BlogPost${blog_post_id} from '../${blog_post_id}/+page.svelte';
							</script>

							<BlogPost${blog_post_id} />

							<!-- generated by ${origin_path} -->
						`,
				});
			}
		}
	}

	return outputs;
};
